CREATE TABLE IF NOT EXISTS student
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    date_of_birth DATE         NOT NULL,
    group_number  VARCHAR(109) NOT NULL
);

INSERT INTO student (name, date_of_birth, group_number)
VALUES ('Иванов Иван', '2000-01-15', '121'),
       ('Петров Петр', '1999-05-23', '431'),
       ('Сидоров Сидор', '2001-08-30', '231');
